const List<String> majorsList = [
  'Agriculture and Agriculture Operations',
  'Architecture and Related Services',
  'Area, Ethnic, Cultural, Gender, and Group Studies',
  'Biological and Biomedical Sciences',
  'Business, Management, Marketing',
  'Communication, Journalism, and Related Programs',
  'Computer and Information Sciences',
  'Education',
  'Engineering',
  'English Language and Literature/letters',
  'Foreign Languages, Literatures, and Linguistics',
  'Health Professions and Related Programs',
  'History',
  'Human Services',
  'Legal Professions and Studies',
  'Liberal Arts and Sciences Studies and Humanitie\'s',
  'Mathematics and Statistics',
  'Mechanic and Repair Technologies/technicians',
  'Military Technologies and Applied Sciences',
  'Philosophy and Religious Studies',
  'Psychology',
  'Science Technologies/technicians',
  'Social Sciences',
  'Theology and Religious Vocations',
  'Visual and Performing Arts',
];

const List<String> countriesList = [
  'Norway',
  'Switzerland',
  'Ireland',
  'Germany',
  'Hong Kong',
  'Australia',
  'Iceland',
  'Sweden',
  'Singapore',
  'Netherlands',
  'Finland',
  'Canada',
  'New Zealand',
  'United Kingdom',
  'United States',
  'Belgium',
  'Japan',
  'South Korea'
];

class CoinData {}
